name = "EtherHeaders"
uuid = "3e86acbe-5540-45e9-bcfe-e06192d9613f"
authors = ["ChenyuBao <chenyu.bao@outlook.com>"]
version = "0.1.7"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = ">=1.11.0"
